// Generated by Grafana k6 Studio (1.10.0) on 2026-02-09T10:13:28.326Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 10, duration: "1m" },
    { target: 10, duration: "3m" },
    { target: 0, duration: "1m" },
  ],
  cloud: {
    distribution: {
      "amazon:it:milan": { loadZone: "amazon:it:milan", percent: 100 },
    },
  },
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    params = {
      headers: {
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://blazedemo.com/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "cache-control": `max-age=0`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        origin: `https://blazedemo.com`,
        "content-type": `application/x-www-form-urlencoded`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://blazedemo.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://blazedemo.com/reserve.php`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(`{"fromPort":"Paris","toPort":"Buenos Aires"}`),
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "cache-control": `max-age=0`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        origin: `https://blazedemo.com`,
        "content-type": `application/x-www-form-urlencoded`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://blazedemo.com/reserve.php`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://blazedemo.com/purchase.php`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(
        `{"flight":"43","price":"472.56","airline":"Virgin America","fromPort":"Paris","toPort":"Buenos Aires"}`,
      ),
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "cache-control": `max-age=0`,
        "sec-ch-ua": `"Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        origin: `https://blazedemo.com`,
        "content-type": `application/x-www-form-urlencoded`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://blazedemo.com/purchase.php`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://blazedemo.com/confirmation.php`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(
        `{"_token":"","inputName":"Tommaso","address":"123 Main","city":"Rome","state":"Italy","zipCode":"1234","cardType":"visa","creditCardNumber":"123456789","creditCardMonth":"11","creditCardYear":"2017","nameOnCard":"Tommaso"}`,
      ),
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(3);
}
